name: CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  client:
    name: Client Build & Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './client/package-lock.json'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build client
        run: npm run build

      - name: Run tests
        run: npm test -- --coverage --ci --watchAll=false
        env:
          CI: true

  server:
    name: Server Build & Test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './server/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build server
        run: npm run build

      - name: Run tests
        run: npm test -- --ci
        env:
          CI: true

  # This job will only pass if both client and server jobs pass
  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [client, server]
    steps:
      - name: Mark CI as successful
        run: echo "All CI checks passed successfully!"
