name: Smoke Tests

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]
    branches: [main]

jobs:
  smoke-tests:
    # Only run smoke tests if the CI workflow completed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: self-hosted
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Wait for staging deployment
        run: |
          echo "Waiting for staging deployment to be ready..."
          sleep 45

      - name: Health check staging
        run: |
          echo "Checking staging health..."
          curl -f ${{ secrets.STAGING_URL }}/health || exit 1

      - name: Install e2e test dependencies
        run: |
          cd e2e
          npm ci
          npx playwright install chromium
          npx playwright install-deps

      - name: Run smoke tests
        run: |
          cd e2e
          BASE_URL=${{ secrets.STAGING_URL }} npm run test:local
        env:
          CI: true
        continue-on-error: true

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: smoke-test-results
          path: |
            e2e/test-results/
            e2e/playwright-report/
          retention-days: 7

      - name: Comment on commit with results
        if: always()
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "✅ Smoke tests passed against staging environment"
          else
            echo "⚠️ Smoke tests failed - check artifacts for details"
          fi